enum MessageId {
    // ID for static data on UI
    CUSTOMERS = "CUSTOMERS",

    DASHBOARD = "DASHBOARD",

    PARTNERS = "PARTNERS",

    LOGIN = "LOGIN",

    REGISTRATION = "REGISTRATION",

    PASSWORD = "PASSWORD",

    LOGIN_FAILED = "LOGIN_FAILED",

    EMAIL = "EMAIL",

    FIRST_NAME = "FIRST_NAME",

    LAST_NAME = "LAST_NAME",

    CONFIRM_PASSWORD = "CONFIRM_PASSWORD",

    REGISTRATION_REDIRECT = "REGISTRATION_REDIRECT",

    REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS",

    REGISTRATION_SUCCESS_CONTENT = "REGISTRATION_SUCCESS_CONTENT",

    SERVER_ERROR = "SERVER_ERROR",

    SERVER_ERROR_CONTENT = "SERVER_ERROR_CONTENT",

    REGISTRATION_FAILED = "REGISTRATION_FAILED",

    REGISTRATION_FAILED_CONTENT = "REGISTRATION_FAILED_CONTENT",

    PLACEHOLDER_SEARCG_STORE = "PLACEHOLDER_SEARCG_STORE",

    STORES = "STORES",

    SEARCH = "SEARCH",

    NAME = "NAME",

    ADDRESS = "ADDRESS",

    TAX_CODE = "TAX_CODE",

    PHONE_NUMBER = "PHONE_NUMBER",

    CONTACT_NAME = "CONTACT_NAME",

    EMPLOYEE = "EMPLOYEE",

    ACTION = "ACTION",
}

export default MessageId;
