enum MessageId {
    // ID for static data on UI
    CUSTOMERS = "CUSTOMERS",

    DASHBOARD = "DASHBOARD",

    PARTNERS = "PARTNERS",

    LOGIN = "LOGIN",

    REGISTRATION = "REGISTRATION",

    PASSWORD = "PASSWORD",

    LOGIN_FAILED = "LOGIN_FAILED",

    EMAIL = "EMAIL",

    FIRST_NAME = "FIRST_NAME",

    LAST_NAME = "LAST_NAME",

    CONFIRM_PASSWORD = "CONFIRM_PASSWORD",

    REGISTRATION_REDIRECT = "REGISTRATION_REDIRECT",

    REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS",

    REGISTRATION_SUCCESS_CONTENT = "REGISTRATION_SUCCESS_CONTENT",

    SERVER_ERROR = "SERVER_ERROR",

    SERVER_ERROR_CONTENT = "SERVER_ERROR_CONTENT",

    REGISTRATION_FAILED = "REGISTRATION_FAILED",

    REGISTRATION_FAILED_CONTENT = "REGISTRATION_FAILED_CONTENT",

    PLACEHOLDER_SEARCG_STORE = "PLACEHOLDER_SEARCG_STORE",

    STORES = "STORES",

    SEARCH = "SEARCH",

    NAME = "NAME",

    ADDRESS = "ADDRESS",

    TAX_CODE = "TAX_CODE",

    PHONE_NUMBER = "PHONE_NUMBER",

    CONTACT_NAME = "CONTACT_NAME",

    EMPLOYEE = "EMPLOYEE",

    ACTION = "ACTION",

    CUSTOMERS_DETAIL = "CUSTOMERS_DETAIL",

    NOT_FOUND = "NOT_FOUND",

    CUSTOMER_NOT_FOUND = "CUSTOMER_NOT_FOUND",

    CUSTOMER_NAME = "CUSTOMER_NAME",

    UPDATE = "UPDATE",

    DELETE = "DELETE",

    CONFIRM_DELETE = "CONFIRM_DELETE",

    CONFIRM_DELETE_DETAIL = "CONFIRM_DELETE_DETAIL",

    CONFIRM_UPDATE = "CONFIRM_UPDATE",

    CONFIRM_UPDATE_DETAIL = "CONFIRM_UPDATE_DETAIL",

    CANNOT_DELETE = "CANNOT_DELETE",

    CANNOT_DELETE_DETAIL = "CANNOT_DELETE_DETAIL",

    DELETE_SUCCESS = "DELETE_SUCCESS",
    DELETE_SUCCESS_DETAIL = "DELETE_SUCCESS_DETAIL",
}

export default MessageId;
